FROM almalinux
ADD https://github.com/techworldwithsiva/docker-install-commands/blob/master/docker-commands.MD/tmp
RUN wget -y
ADD https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.78/bin/apache-tomcat-9.0.78.tar.gz/tmp